### ISSUE TITLE
P8: Double tap too sensitive

### ISSUE THREAD

**Issue by MatsFisk** [enaon/eucWatch#1]
EDIT#3: I forked it to a P8-specific repo. 

-----------------------------------

Hi! First off, amazing work. Like seriously, this is awesome. I'd contribute, but I'm not sure I have enough spare time; my contributions might be outdated before I can finish them. We'll see. 

I have some either issues or suggestions, though I'm not sure whether this one is a feature or bug. The interval that decides whether it's a double tap or not seems to be too long. When I'm using the calculator, for instance, the screen suddenly goes black, since it registered my inputs as a double tap. The same happens when I'm in the menu. I'm not sure if this happens to other people, though, so I guess it's just a preference/judgement call. 

My suggestion is to either 
- make the interval shorter overall
- make it shorter when the screen is on, so slow double taps when the screen is off still wakes the screen
- make the interval shorter when in apps or the menu
- add these as options to settings (probably messy with such a small screen)
- add these as options when uploading Handler

If this isn't a high priority issue for you, it sounds like it should be a fairly (probably super) easy fix which might be a good introduction for me to the world of Espruino. It sounds like the easiest fix is to simply change a single variable. I'm a js developer, after all. I'll can take a look at it. 

EDIT: If you prefer me to fork rather than contribute (I have little interest in the euc-part of your project, for instance), then let me know.

**Comment by enaon** [comment]
thank you for your kind words, I am glad you like it. It has code from a lot of people, I will update the credits. 

Thank you for your input too, I am trying to understand when this happens. Double tap is only used to wake the screen when off, and only on the 816 controller, And even then, it does nothing if the sceen is on, it just two single taps, and each tap resets the off screen timer. Actually there is no double tap event reported from the touch controler, I only scan for a pair of single taps when sleeping. 

I tried to simulate the problem on a 816 based watch and it seems to work ok. 
On which controller does the problem appear?

**Comment by enaon** [comment]
` When I'm using the calculator, for instance, the screen suddenly goes black, since it registered my inputs as a double tap. `

I think I see what may be happning. The only way to have the screen turn black when on calculator, clock, events, or alarm face, is to do a down gesture. Maybe this is what you are doing, or maybe the controler mistakes two short taps for a down slide. If you have some time try to verify which one is your case.

**Comment by MatsFisk** [comment]
I have the 816s. And you're right. What happens is that I hit between the buttons/clickable areas, and as I press my finger slides very slightly downwards, which triggers the screen blackout. Maybe there should be a longer minimum length on this slide? But if you guys haven't experienced this problem then maybe it's just me who has to learn to press a screen properly, haha.

**Comment by enaon** [comment]
I will have a look, the 816s gesture margins are settable, the interrupt fires every 10ms or so and only reports gestures after the finger leaves the screen, thus I am ingoring it and use custom polling.

**Comment by enaon** [comment]
I pushed a change, no version change so just reupload handler. 

the margins went from 20 to 35, if you have some time please report if it works better now.

**Comment by MatsFisk** [comment]
It works perfectly, thanks!

**Comment by enaon** [comment]
nice, thank you for the feedback.
