### ISSUE TITLE
sensor p22

### ISSUE THREAD

**Issue by rosciio** [enaon/eucWatch#18]
hello
I'm trying to use sensors of my P22.
which app can I use?

Thanks

Good work

**Comment by enaon** [comment]
hi, the sensors that are working are the touch and accel, I do not use heart rate sensor, but it is doable.
Is that what you are after?

**Comment by rosciio** [comment]
Yes, i would like see my heart sensor for a example. Do you have same template or function that I can use?

**Comment by enaon** [comment]
getting the HR working is no easy task using javascript, precise timing is importand.

jeffmer has a custom image that supports it, but the free mem on this one is low. You could use his screen driver to save on ram, but then screen refresh will become slow.

https://github.com/jeffmer/WatchApps/tree/master/firmware

**Comment by rosciio** [comment]
I will try  and report result if I can
thanks
