### ISSUE TITLE
InMoution V12 support

### ISSUE THREAD

**Issue by Zimines** [enaon/eucWatch#19]
Dear developer.
Could you please add InMoution V12 support to your eucWatch , that I love so much and used it with my old V5 euc.
But now i have new V12 wheel and want to continue use your eucWatch with it also.
Thanks for your work! It awesome!!!

Ready to provide any possible logs or anythink else from my v12 to support this.

**Comment by enaon** [comment]
I will give it a go yes, sorry for the delay.
