### ISSUE TITLE
Kingsong s22 and begode master

### ISSUE THREAD

**Issue by The-Curious-Kiwi** [enaon/eucWatch#22]
Just wondering if anyone is working on the s22 and master comparability. Also is there somwhere people can donate to the cause as i put this onto watches for other people at no charge and each time i do it i feel like they should donate to the cause

**Comment by ggriffin924** [comment]
Same thoughts here, I have the S22 and use the EUCwatch for my other EUC's currently.  Hoping to get S22 support at some point.

**Comment by denesterov** [comment]
Ifaik there is support for S22, but only in newest versions of EUCWatch. So people with older hardware watch, like P22C1, cannot use them with S22
:(
