### ISSUE TITLE
P22(D) pinout

### ISSUE THREAD

**Issue by jawsh207** [enaon/eucWatch#23]
Where can I find the pinout info these watches use? Working on helping get Wasp-OS support for them (p8 is already supported) but need to provide pinout info. Not really a eucWatch issue but not sure how else to ask. The more options to make these cheap watches usable and supported by other projects as well, the better!

**Comment by enaon** [comment]
Very similar to the pinetime, basics pins are :

ew.pin = { BAT: D31, CHRG: D19, BUZZ: D16, BUZ0: 1, BL: D12, i2c: { SCL: D7, SDA: D6 }, touch: { RST: D10, INT: D28 }, disp: { CS: D25, DC: D18, RST: D26, BL: D14 }, acc: { INT: D8 } } ;
