### ISSUE TITLE
Installed on new P8b variant, screen mirrored, wanna switch back to infinitime thx.

### ISSUE THREAD

**Issue by ccchan234** [enaon/eucWatch#25]
hi, i guess my new p8b is p8b-2, the mirrored one. i followed this and is on espurino but screen is inverted. may be infinitime support this variant. any idea how to get back to it? the watch is not bricked, in daflasher i can press start bootloader (what sdk12 i think) and can connect as dfuart? and flash the espurino system into it (but not bootloader anymore) thx.   (i.e. step 4)
https://enaon.github.io/eucWatch/tools/hackme/

mine could be the mirrored one of P8b
https://github.com/StarGate01/p8b-infinitime/blob/master/HardwareVariants.md

thx

**Comment by Somnius** [comment]
You need to change the core from the web installer to one of the others on install all, so the screen can be recognized properly.
