### ISSUE TITLE
inmotion v14

### ISSUE THREAD

**Issue by eried** [enaon/eucWatch#26]
Hi, I am looking for the "horn" code for the inmotion v14 adventure, is this -> https://github.com/enaon/eucWatch/blob/f5d4d79538c413a2dd5a158438449b11bbbbd0e2/P8/eucInmotion/eucInmotionV14.js#L4 tested on a v14 or it is just adapted from older versions?

(I havent got a hw BLE sniffer yet :/ )

**Comment by enaon** [comment]
Hi, this is a very old file, v14 stands for firmware version 1.4, not the model V14 :)

You can find the horn code here:
https://github.com/enaon/eucWatch/blob/f5d4d79538c413a2dd5a158438449b11bbbbd0e2/v2/euc/eucInmotionV2/eucInmotionV2.js#L498
