### ISSUE TITLE
P22B1 Bluetooth keeps disconnecting

### ISSUE THREAD

**Issue by madx** [enaon/eucWatch#28]
Hello @enaon! First, thanks for this cool project!

I installed eucWatch for my P22B1. Everything seemed to be fine, except I had to use nRF Connect to install the step2 file (as you suggested in another comment here).

I tried to setup Gadgetbridge and shortly after (I'm not sure this is related) I tried to install other apps, but my device keeps disconnecting from the BLE connection, no matter which device I try to connect with.

I've tried:

- eucWatch Loader app on Chrome/Linux: disconnects a few second after connecting
- eucWatch Loader app on Chrome/Android: same
- Reconnecting through Gadgetbridge: same
- Connecting with nRF Connect: same (I thought I could re-do the flash process)
- Same with DaFlasher

Do you have any idea of what could be happening?

Some addition troubleshooting info:

- I installed the core and handler files for P22B1, but I did not use Install all apps as I wanted to only pick some select ones. I've read in another topic that this might be an issue
- Using nRF Connect, I sometimes get this error in the logs when trying to connect (e.g. with DaFlasher)

```
Connection Parameters update failed with status 19
Error 19 (0x13): UNKNOWN (19)  
```

**Comment by enaon** [comment]
Sory for the delayed answer, I am not sure what is happening in your case, but not installing all apps may be the problem, there may be important files missing.

There is devmode in any case, You can hold the side button for over 40 secs, you will feell a buzz, wait 3-4 secs more and then release the button. Scan for a espruino-devmode device and try to connect, it will only load the init and the watchdog (the screen will be black) Use this mode to reupload everything, and try again. 

To exit devmode, short press the side button, or press the disconnect button on the loader (if you are connected).

**Comment by madx** [comment]
Thanks, I will give it a shot!

**Comment by enaon** [comment]
@madx, one more think, I missed the part about GadgetBridge. Maybe at the tme you enabled GB support on the watch, you disabled the CLI, this is needed for loader access. In the BT menu, make sure CLI is blue. Maybe it is just that.
