### ISSUE TITLE
eucWorld.js

### ISSUE THREAD

**Issue by Somnius** [enaon/eucWatch#4]
I see that it asks for specific service thru uuid and checks for values, is "eucWorld.js" a bridge to EucWorld android app ?

**Comment by enaon** [comment]
yes, but replaced by eucEmu now, leave it for later I think :)

**Comment by Somnius** [comment]
OK, I can ask for help on EUC.world from the author, whenever is needed, but I don't know anything about eucEmu. Care to share some info?

**Comment by enaon** [comment]
it is related to this video, I am testing the idea of having the watch emulate the wheel so that a phone can connect, it is a bridge with privilages, I called it eucWorld because this is what I have in mind, but is could be any app. 

https://www.youtube.com/watch?v=veTZA-ubmdA
