### ISSUE TITLE
Begode mten3 Voltage is wrong

### ISSUE THREAD

**Issue by bobpaul** [enaon/eucWatch#8]
I have a Begode mten3.

Using a multimeter I measure 78.2v at the charge connector. 
The watch shows 94.2v / 75%.
[WheelLog android app](https://github.com/Wheellog/Wheellog.Android) shows 78.5v/69%

**Comment by enaon** [comment]
hi, the mpotherboard of all begode wheels, from mten3 to monster pro, report as 67 volt. 

to change base (67/84/100) long hold on the battery field when on the digital dash.  

Percentage depends on minimum allowed voltage allowed, and that is wheels specific, I will later make it customizable, but don't expect it to be the same as euc world, it is an estimation, gotways do not report battery percentage.

**Comment by bobpaul** [comment]
Oh, thanks! I changed the voltage and now things look better.
