### ISSUE TITLE
P22 Drivers

### ISSUE THREAD

**Issue by vjapolitzer** [enaon/eucWatch#9]
Hello,

Thanks for all our amazing work on this! I successfully got it running on a P22 (P22B?)! However, touch (and possibly accel) are not quite working right.
The driver that works the _best_ for touch is the 816 driver, but taps are not recognized, only swipes and long presses. It also wakes from a down swipe.  
I think the touch controller IC may be the 716S or something like that? I took apart the watch to get a closer look at its components.  
![WIN_20210607_11_09_29_Pro](https://user-images.githubusercontent.com/4155688/121068325-fed44e80-c780-11eb-8a30-04fa99c609aa.jpg)  
Raise to wake does not work for either BMA421 or SC7A20 driver. Maybe I am misunderstanding how that is supposed to work. I can take a closer look if the pinout is changed or something, let me know!  
![WIN_20210607_11_15_49_Pro](https://user-images.githubusercontent.com/4155688/121073835-e7e52a80-c787-11eb-93ac-db4e8f435b03.jpg)  
FCC also has some nice photos of the inside: https://fccid.io/2AGFWP22/Internal-Photos/Internal-Photos-4786333  

Best,  
Vincent

**Comment by enaon** [comment]
thank you very much for all the info, I have a p22 coming and will try to see what is different. 

three p8s came this week, all ton, all working, it seems that only utelite store from ali has the non compatible ones until now, maybe I spoke too soon about end on line for the p8.

**Comment by tyrone1984** [comment]
I had one too

SPIFLASH 
pin_sck D2
pin_mosi D3
pin_miso D4
pin_cs D5

D15 BTN1
D16 VIBRATE
D19 Charging(BAT)

D22 BackLight

**Comment by enaon** [comment]
thank you very much

so it uses d15 for the button and only uses d22 for brighntess, d14 and d23 are not used?

**Comment by tyrone1984** [comment]
Sorry I don't know how to   detect  pin,  but  the touch IC is cst816  when I opened it

**Comment by enaon** [comment]
> Vincent

Thank you for the info, is the side button working on your p22b? 
it is on a different pin on the p22 it seems, d15 instead of D17 for the p8.

**Comment by vjapolitzer** [comment]
> > Vincent
> 
> is the side button working on your p22b?
> it is on a different pin on the p22 it seems, d15 instead of D17 for the p8.

No, it is not working. When I get a chance I can pop mine open again and check the pins.

**Comment by enaon** [comment]
> > > Vincent
> > 
> > 
> > is the side button working on your p22b?
> > it is on a different pin on the p22 it seems, d15 instead of D17 for the p8.
> 
> No, it is not working. When I get a chance I can pop mine open again and check the pins.

thanks, use this image, it makes the button work ok. 

https://github.com/fanoush/ds-d6/blob/master/espruino/DFU/P8/espruino_2v09.119_p22_SDK12_SD30_SPIFLASH4M.zip

**Comment by enaon** [comment]
> but taps are not recognized

if you have some time, reload the handler(select 816) file from https://enaon.github.io/eucWatch/p8-testing
and connect to the watch using the ide: https://www.espruino.com/ide/

it will spill out the touch values on the left side, if you can please upload the outpout on a tap.

**Comment by vjapolitzer** [comment]
> > but taps are not recognized
> 
> if you have some time, reload the handler(select 816- restart after upload) file from https://enaon.github.io/eucWatch/p8-testing
> and connect to the watch using the ide: https://www.espruino.com/ide/
> 
> it will spill out the touch values on the left side, if you can please upload the output on a tap.

The new espruino image does indeed make the button work!  
Here are some outputs from the IDE:
```
// Four Swipes, seems to be working fine
new Uint8Array([0, 4, 1, 128, 40, 0, 118])
new Uint8Array([0, 3, 1, 128, 192, 0, 133])
new Uint8Array([0, 2, 1, 128, 134, 0, 146])
new Uint8Array([0, 1, 1, 128, 128, 0, 43])

// Four long presses (registers only after releasing finger)
new Uint8Array([0, 12, 1, 128, 16, 0, 112])
new Uint8Array([0, 12, 1, 128, 165, 0, 106])
new Uint8Array([0, 12, 1, 128, 30, 0, 115])
new Uint8Array([0, 12, 1, 128, 88, 0, 16]

// Four taps
new Uint8Array([0, 0, 0, 64, 10, 0, 24])
new Uint8Array([0, 0, 0, 64, 222, 0, 14])
new Uint8Array([0, 0, 0, 64, 9, 0, 128])
new Uint8Array([0, 0, 0, 64, 207, 0, 111])
```

**Comment by enaon** [comment]
thanks!. Please reload the handler, taps should now work. 

https://enaon.github.io/eucWatch/p8

**Comment by enaon** [comment]
> // Four taps
> ```

**Comment by vjapolitzer** [comment]
Excellent - taps are working great, thanks! Additionally, since now I am able to toggle the raise-to-wake function, I can confirm SC7A20 driver is working with my P22.

**Comment by enaon** [comment]
very nice, can you please post a link of where you got it from?

**Comment by vjapolitzer** [comment]
Sure,
https://www.amazon.com/IDEALROYAL-Smartwatch-Fitness-Tracker-Bluetooth/dp/B08TLMGWXJ/
IDEALROYAL branded _Black_ P22 from Amazon seller, Meixiong US. $24.99 (USD) with Prime shipping after coupon (don't know how long the coupon will last)
